version: '3'

services:
  postgres:
    image: postgres
    container_name: gibspons-postgres
    volumes:
      - postgres-db:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - 5432:5432
    networks:
      - gibspons-network
  
  gibspons-api:
    image: aarabi/gibspons-gibspons-api:latests
    container_name: gibspons-api
    ports:
      - 8000:8000
    volumes:
      - .:/usr/src/gibspons/
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - gibspons-network
    restart: always
    
  traefik:
    build:
      context: .
      dockerfile: ./traefik/Dockerfile
    container_name: gibspons-traefik
    depends_on:
      - gibspons-api
    volumes:
      - traefik-volume:/etc/traefik/acme:z
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
      - "0.0.0.0:5555:5555"
    networks:
      - gibspons-network
    restart: always
      
volumes:
  postgres-db:
  traefik-volume:

networks:
  gibspons-network: