# Generated by Django 4.2.6 on 2024-01-03 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sponsorship_app', '0002_organisation_user_invite_code_user_organisation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date_of_event', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_company', models.CharField(max_length=255)),
                ('company_type', models.CharField(max_length=100)),
                ('name_of_poc', models.CharField(max_length=100)),
                ('position_of_poc', models.CharField(max_length=100)),
                ('email_poc', models.EmailField(max_length=254)),
                ('sponsorship_ask', models.CharField(max_length=100)),
                ('linkedin', models.URLField()),
                ('website', models.URLField()),
                ('details', models.CharField(max_length=500)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sponsorship_app.event')),
            ],
        ),
    ]
