# Generated by Django 5.0.1 on 2024-02-05 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_organisation'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='industry',
            field=models.CharField(default='Tech', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organisation',
            name='location',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='organisation',
            name='logo',
            field=models.URLField(null=True,blank=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='points',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='user1', max_length=254),
            preserve_default=False,
        ),
    ]
