# Generated by Django 4.2.6 on 2024-01-30 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spons_app', '0004_sponsorship_remove_event_money_raised_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='domain',
            new_name='industry',
        ),
    ]
