# Generated by Django 5.0.1 on 2024-02-07 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spons_app', '0007_delete_organisation_company_linkedin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsorship',
            name='additional',
            field=models.CharField(null=True),
        ),
    ]
