# Generated by Django 5.0.1 on 2024-02-07 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spons_app', '0008_alter_sponsorship_additional'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='logo',
            field=models.URLField(null=True),
        ),
    ]
