# Generated by Django 5.0.1 on 2024-04-10 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spons_app', '0009_event_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='spons_app.event'),
        ),
    ]
