# Generated by Django 5.0.1 on 2024-04-10 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spons_app', '0010_company_event'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='date_of_event',
            new_name='end_date',
        ),
        migrations.AddField(
            model_name='event',
            name='start_date',
            field=models.DateField(default='2024-01-01'),
            preserve_default=False,
        ),
    ]
