# Generated by Django 5.0.1 on 2024-04-12 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spons_app', '0011_rename_date_of_event_event_end_date_event_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='poc',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='spons_app.event'),
            preserve_default=False,
        ),
    ]
