# Generated by Django 5.0.1 on 2024-04-14 17:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spons_app', '0012_poc_event'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Company', 'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
        migrations.AlterUniqueTogether(
            name='company',
            unique_together={('name', 'website')},
        ),
        migrations.RemoveField(
            model_name='poc',
            name='event',
        ),
        migrations.AddField(
            model_name='sponsorship',
            name='contacted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sponsorship',
            name='poc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='spons_app.poc'),
        ),
        migrations.AddField(
            model_name='sponsorship',
            name='status',
            field=models.CharField(choices=[('No Reply', 'No Reply'), ('In Progress', 'In Progress'), ('Rejected', 'Rejected'), ('Accepted', 'Accepted')], default='Not Contacted', max_length=20),
        ),
        migrations.AddField(
            model_name='sponsorship',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='sponsorship',
            name='money_donated',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='sponsorship',
            name='type_of_sponsorship',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.RemoveField(
            model_name='company',
            name='event',
        ),
        migrations.RemoveField(
            model_name='company',
            name='status',
        ),
        migrations.RemoveField(
            model_name='company',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='company',
            name='user_id',
        ),
    ]
