# Generated by Django 5.0.1 on 2024-04-16 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spons_app', '0014_alter_sponsorship_status'),
        ('users', '0013_user_profile_pic'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='company',
            unique_together={('name', 'website', 'organisation')},
        ),
    ]
