# Generated by Django 4.2.6 on 2024-01-11 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='organisation',
            new_name='organisation_id',
        ),
    ]
