# Generated by Django 4.2.6 on 2024-01-17 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_organisation_user_organisation_id'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.RenameField(
            model_name='user',
            old_name='organisation_id',
            new_name='organisation',
        ),
    ]
